modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="phantazmmod"
version="1.0"
displayName="PhantazmMod" #mandatory
authors="MCMaximilian"
# I copied syeyoun( cyoung06's code )
# Cyoung06's Github: https://github.com/cyoung06/ZombiesCorneringMod
description='''
Phantazm Zombies Server's Mod!
'''
